# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='faved_by',
            field=models.ManyToManyField(blank=True, related_name='favquotes', to='registration.User'),
        ),
    ]
