# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171220_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='faved_by',
            field=models.ManyToManyField(related_name='favquotes', to='registration.User'),
        ),
    ]
